### ISSUE TITLE
How to Include RSS-Feed for the Article Page

### ISSUE THREAD

**Issue by ghost** [mecha-cms/x.feed#1]
Hi,
My question would be, how can I integrate the RSS feed on my articles page at https://mechacms.wpzweinull.ch? 

I would like it so that the blog readers can subscribe to the RSS feed from the home page. 

I would then have to embed somewhere in the template.

How can I best realize it?

Thanks in advance.

**Comment by taufik-nurrohman** [comment]
Just add `feed.rss` at the end of the URL:

~~~
http://example.com/article
~~~

~~~
http://example.com/article/feed.rss
~~~

Register that URL to the RSS feed service such as _Google Feedburner_.

This extension currently not maintained and will simply show the whole page list, I will consider to add pagination next time.

https://tools.ietf.org/html/rfc5005#section-3

**Comment by ghost** [comment]
Thanks, has just worked well under `/blog` with me and so I can integrate the RSS feed for the first time, so that the readers have access to it.

The "Homepage" has with me but no RSS feed. Something like `/article` I did not. I only have the blog under `/blog` and articles appear directly on the home page. That was different.

But well, I am now informed and we can close the issue.
